### ISSUE TITLE
RSS Feed for Blog

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-roq#116]
One of the things Gatsby does is it generates this in the `<head>`

```xml
<link rel="alternate" type="application/rss+xml" title="Melloware Blog" href="[/rss.xml]"/>
```

and example of the RSS feed it generates is

https://www.melloware.com/rss.xml

**Comment by ia3andy** [comment]
Yeah this, sitemap and search were in my head.. should be easy now with my recent changes..

**Comment by melloware** [comment]
We could code by hand or use this zero dependency RSS lib.

https://github.com/w3stling/rssreader

Its nice and its just 100% java with nothing else

**Comment by melloware** [comment]
No I think we still want to work on it.

**Comment by ia3andy** [comment]
Yeah I need to allow different kind of files

**Comment by ia3andy** [comment]
This one is for you :)

**Comment by melloware** [comment]
Andy any guidance on the best way to accomplish this?  Even just some pseudo-code steps?

The idea I assume is to as part of the build generate a static `rss.xml` file and then add a Qute tag to expose the URL like...

`xml
<link rel="alternate" type="application/rss+xml" title="Melloware Blog" href="[/rss.xml]"/>
```

**Comment by ia3andy** [comment]
@melloware I would go for:
- 1 include (similar to paginate) for the rss.xml (fm/rss.xml)
- 1 tag for `<link rel="alternate" type="application/rss+xml" title="Melloware Blog" href="[/rss.xml]"/>`

In the include you will need to iterate on the given collection name like it's done in the index.html, have a look at the blog tag page to read the collection from a parametrised name.

**Comment by melloware** [comment]
Love it will work on this ASAP.
