### ISSUE TITLE
Create Credits page with contributors

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#125]
Add all-contribs
Automate copy of all-contribs json files and print the content in the blog

**Comment by ia3andy** [comment]
@melloware would you add the all-contributor? I'll take care of creating the credit page on the blog :)

**Comment by melloware** [comment]
@all-contributors add @ia3andy for maintenance, code

**Comment by melloware** [comment]
@all-contributors add @mcruzdev for code,ideas

**Comment by melloware** [comment]
@all-contributors add @melloware for code

**Comment by melloware** [comment]
@all-contributors add @maxandersen for ideas,bug

**Comment by melloware** [comment]
@all-contributors add @holly-cummins for idea

**Comment by melloware** [comment]
Done!
