### ISSUE TITLE
why is "date" a timestamp

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-roq#134]
"date" is being enforced to be a full timestamp.

`date: 2024-08-29` vs `date: 2024-08-29 13:32:20 +0200`

is that expected? 

shouldn't it be called `timestamp` if really after that precision or at least be lenient when parsing it so `date: 2024-08-29` is accepted ?

**Comment by melloware** [comment]
I could go either way but it's also used for sorting your blog posts so if you were prolific and posted 3 blogs on the same day i guess the order would be random for those and not in the exact order you posted?

But more importanlty Gatsby has a formatString so `formatString: "LL",` comes out "August 24, 2008" while `formatString: "DD-MM-YYYY", comes out on your blog as "24-08-2024".

So i am OK its a timestamp its just we should allow rendering control?  So in my FrontMatter I write this.

```
---
title: "PrimeFaces 14.0.0 Release"
date: 2024-05-01
tags:
  - PrimeFaces
  - JSF
  - Faces
banner: ./primefaces-logo.webp
---
```

And it comes out

![image](https://github.com/user-attachments/assets/488da0d8-be2f-4d67-be9f-0af591cb52e8)

**Comment by ia3andy** [comment]
https://github.com/quarkiverse/quarkus-roq/blob/main/roq-frontmatter/deployment/src/main/java/io/quarkiverse/roq/frontmatter/deployment/RoqFrontMatterConfig.java#L53

**Comment by ia3andy** [comment]
It uses Jekyll default, but you can adjust it with config..

**Comment by ia3andy** [comment]
We could detect the size and support both by default I guess

**Comment by maxandersen** [comment]
> It uses Jekyll default, but you can adjust it with config..

jekylls default is:

```
A date here overrides the date from the name of the post. This can be used to ensure correct sorting of posts. A date is specified in the format YYYY-MM-DD HH:MM:SS +/-TTTT; hours, minutes, seconds, and timezone offset are optional.
```

meaning YYYY-MM-DD works and the full timestamp is optional. just parse with one first, then if that fails, parse with second?

**Comment by ia3andy** [comment]
Thanks @maxandersen yeah that makes sense :)

Date is parsed here: https://github.com/quarkiverse/quarkus-roq/blob/main/roq-frontmatter/deployment/src/main/java/io/quarkiverse/roq/frontmatter/deployment/scan/RoqFrontMatterScanProcessor.java#L166-L171
and filename is available.

The idea is to have the `dateValue = fm.getString(DATE_KEY, extract the date from the filename, or null)`
Add this as default date format in config: `yyyy-MM-dd[ HH:mm][:ss][ Z]`, then we need to adapt depending on what's provided like this:
```java
public static ZonedDateTime parseDateTime(String input) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd[ HH:mm][:ss][ Z]");
        try {
            // Try parsing as a ZonedDateTime directly (with time and zone).
            return ZonedDateTime.parse(input, formatter);
        } catch (DateTimeParseException e1) {
            try {
                // If that fails, try parsing as a LocalDateTime and assign a default time zone.
                LocalDateTime localDateTime = LocalDateTime.parse(input, formatter);
                return localDateTime.atZone(ZoneId.systemDefault()); // Use system default zone.
            } catch (DateTimeParseException e2) {
                // If that fails, parse as a LocalDate and assign default time and zone.
                LocalDate localDate = LocalDate.parse(input, formatter);
                return localDate.atStartOfDay(ZoneId.systemDefault()); // Start of the day with default zone.
            }
        }
    }

```

@edewit want that one?

**Comment by ia3andy** [comment]
This is just to parse the date, for rendering this is a different matter and should be solve with Qute. I think renarde provide some TemplateExtension for dates (cc @FroMage @mkouba ) but I am not sure, anyway we if that doens't exist we should have a qute-web-dates or something to make it easy to render dates..

**Comment by mkouba** [comment]
> This is just to parse the date, for rendering this is a different matter and should be solved with Qute. I think renarde provide some TemplateExtension for dates (cc @FroMage @mkouba ) but I am not sure, anyway we if that doens't exist we should have a qute-web-dates or something to make it easy to render dates..

In Qute core there is https://quarkus.io/guides/qute-reference#time. There's also https://github.com/quarkiverse/quarkus-prettytime extension. But we could create something more convenient...

**Comment by FroMage** [comment]
This is, roughly, what I have:

```java
    public static final String HTML_NORMALISED_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS";
    public static final String HTML_NORMALISED_WITHOUT_SECONDS_FORMAT = "yyyy-MM-dd'T'HH:mm";
    public static final DateTimeFormatter HTML_NORMALISED = DateTimeFormatter
            .ofPattern(HTML_NORMALISED_FORMAT);
    public static final DateTimeFormatter HTML_NORMALISED_WITHOUT_SECONDS = DateTimeFormatter
            .ofPattern(HTML_NORMALISED_WITHOUT_SECONDS_FORMAT);
    public static final DateTimeFormatter HTML_DATE = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    public static final DateTimeFormatter HTML_TIME = DateTimeFormatter.ofPattern("HH:mm:ss");
    public static final DateTimeFormatter HTML_TIME_WITHOUT_SECONDS = DateTimeFormatter.ofPattern("HH:mm");

    public static String prepend(String string, Object value) {
        return value + string;
    }

    public static String append(String string, Object value) {
        return string + value;
    }

    public static String htmlNormalised(Date date) {
        return new SimpleDateFormat(HTML_NORMALISED_FORMAT).format(date);
    }

    public static String htmlNormalised(LocalDateTime date) {
        return date.format(HTML_NORMALISED);
    }

    public static String htmlNormalised(LocalDate date) {
        return date.format(HTML_DATE);
    }

    public static String htmlNormalised(LocalTime date) {
        return date.format(HTML_TIME);
    }

    public static String format(Date date) {
        // FIXME: L10N
        return new SimpleDateFormat("dd/MM/yyyy").format(date);
    }

    public static String internetDateFormat(Date date) {
        return new SimpleDateFormat("yyyy-MM-dd").format(date);
    }

    public static boolean isFuture(Date date) {
        return date.after(new Date());
    }

    public static String since(Date date) {
        LocalDateTime t1 = LocalDateTime.ofInstant(date.toInstant(), ZoneId.systemDefault());
        LocalDateTime t2 = LocalDateTime.now();
        Period period = Period.between(t1.toLocalDate(), t2.toLocalDate());
        Duration duration = Duration.between(t1, t2);

        if (period.getYears() > 1)
            return period.getYears() + " years ago";
        if (period.getYears() == 1)
            return period.getYears() + " year ago";
        if (period.getMonths() > 1)
            return period.getMonths() + " months ago";
        if (period.getMonths() == 1)
            return period.getMonths() + " month ago";
        if (period.getDays() > 1)
            return period.getDays() + " days ago";
        if (period.getDays() == 1)
            return period.getDays() + " day ago";
        if (duration.toHours() > 1)
            return duration.toHours() + " hours ago";
        if (duration.toHours() == 1)
            return duration.toHours() + " hour ago";
        if (duration.toMinutes() > 1)
            return duration.toMinutes() + " minutes ago";
        if (duration.toMinutes() == 1)
            return duration.toMinutes() + " minute ago";
        return "moments ago";
    }
```

**Comment by ia3andy** [comment]
maybe we should move this class to a qute-web artifact @mkouba ?

**Comment by mkouba** [comment]
> maybe we should move this class to a qute-web artifact @mkouba ?

+1 but Renarde does not depend on `qute-web`, or?

Also the `since(Date date)` thing is IMO not very robust (missing localization, etc.). That's why I mentioned `quarkus-prettytime` ;-).

**Comment by ia3andy** [comment]
> > maybe we should move this class to a qute-web artifact @mkouba ?
> 
> +1 but Renarde does not depend on `qute-web`, or?

We could put it in an intermediate artifact so it can be shared.

> 
> Also the `since(Date date)` thing is IMO not very robust (missing localization, etc.). That's why I mentioned `quarkus-prettytime` ;-).

Yeah maybe we could just move it and add support for localization in Steph impl to have something light for Roq.

**Comment by melloware** [comment]
@mkouba i agree someone wrote me about my Gatsby blog and told me my dates were wrong because he was in Germany and my MM.DD.YYYY were opposite of what he was expecting. 😄

**Comment by FroMage** [comment]
It's pretty bare-bones, for sur, I was just telling you what I have, not that it's the best thing :)
