### ISSUE TITLE
Bug when using --- inside a markdown code section

### ISSUE THREAD

**Issue by mcruzdev** [quarkiverse/quarkus-roq#158]
When using the following inside a blog post as markdown:

When you are using `- - - `block.

![image](https://github.com/user-attachments/assets/7428bd38-f18b-4559-a4a1-1837c51f5431)

The page looks like:

Without page content.

![image](https://github.com/user-attachments/assets/ac88e24b-c030-4a35-b1aa-db942dba2814)

**Comment by ia3andy** [comment]
I think there is an issue with the frontmatter regex, I need to fix it
