### ISSUE TITLE
Make sure asciidoc works as expected 

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#169]

**Comment by ia3andy** [comment]
@mkouba do we have a qute-web release with it?

**Comment by mkouba** [comment]
> @mkouba do we have a qute-web release with it?

I will do a release (with both asciidoc and md) tomorrow. It will be `3.2.0`.

**Comment by ia3andy** [comment]
@mcruzdev would you try to add this: https://github.com/quarkiverse/quarkus-qute-web/issues/106 before the release?

**Comment by ia3andy** [comment]
> @mkouba when are you planning to do the release?
> 
> @ia3andy of course!

he just answered (tomorrow)

**Comment by mkouba** [comment]
FYI `qute-web` 3.2.0 is in the Maven central :D

**Comment by ia3andy** [comment]
Ok I am giving it a try

**Comment by jtama** [comment]
Can I help in any way to make asciidoc a thing in roq ?

**Comment by ia3andy** [comment]
Ok @jtama:
- Support is already there (but not tested): https://github.com/quarkiverse/quarkus-roq/blob/main/roq-frontmatter/deployment/src/main/java/io/quarkiverse/roq/frontmatter/deployment/scan/RoqFrontMatterScanProcessor.java#L62 
- You need to create a new plugin quarkus-roq-plugin-asciidoc which depends on qute-web-asciidoc

Then you should be ready to try it :)

**Comment by jtama** [comment]
Ok I will try that and make a PR once it works.

**Comment by jtama** [comment]
Nevermind my previous comment. It works! 

Let me add docs and test where needed. And I will provide a PR.

**Comment by ia3andy** [comment]
@jtama yeah for now it's an empty shell but we might move the logic to it at some point and also for Markdown.. I am not sure yet, so let's keep the option open..

**Comment by ia3andy** [comment]
FYI, the scanner processor is generating a new Qute template with the appropriate markup Qute tag, then Qute is doing the rest using the qute-web extension that allow to use asciidoc and markdown tags.
