### ISSUE TITLE
Implementation of Giscus for the blog

### ISSUE THREAD

**Issue by RayzaAnchayhua** [quarkiverse/quarkus-roq#202]
Hello, everyone!
I would like to know how to implement giscus on the blog to make it more interactive!
I saw it on @mcruzdev 's blog and I think it would be nice to keep the comments for greater interaction with the public!

Link giscus: https://giscus.app/
Link Matheus's blog: https://matheuscruz.dev/2024/02/14/how-quarkus-prepare-reflective-code-to-graalvm/

**Comment by RayzaAnchayhua** [comment]
Yes, I think it would be very interesting to add the giscus!

**Comment by melloware** [comment]
I submitted this: https://github.com/quarkiverse/quarkiverse-devops/pull/303

**Comment by melloware** [comment]
Discussions now available:https://github.com/quarkiverse/quarkus-roq/discussions

**Comment by ia3andy** [comment]
This is done
