### ISSUE TITLE
Allow to use any directory as site root 

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#22]
This would be part of the Statiq config (Deployment)
Default would be `src/main/site` and `data` would be relative to it

This might change the way we scan for files, see Quinoa for example:
https://github.com/quarkiverse/quarkus-quinoa/blob/main/deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java#L358-L378

@melloware this one is for you I guess?

**Comment by melloware** [comment]
Yep you can assign this one to me.
