### ISSUE TITLE
Improve GH Pages deployment 

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#230]
We could probably create a GH action for this.

**Comment by ia3andy** [comment]
@melloware do you want to investigate this?

**Comment by melloware** [comment]
Issue: https://github.com/actions/starter-workflows/issues/2586

PR: https://github.com/actions/starter-workflows/pull/2587

I have no idea if they will accept it

**Comment by melloware** [comment]
Also created PR here: https://github.com/jamstack/jamstack.org/pull/976

Doesn't look like they are too active though

**Comment by jtama** [comment]
As an alternative and while someone takes a look at it, I would find usefull to provide et github repository template.

The following could do the trick : https://github.com/jtama/quarkus-roq-template

**Comment by ia3andy** [comment]
@jtama we could also add it by default in the codestart I suppose

**Comment by jtama** [comment]
can we add github workflows in code start ?

**Comment by ia3andy** [comment]
@jtama yes I think it makes sense to add it in the codestart when we have the actual GitHub action done

**Comment by ia3andy** [comment]
Ok codestart and doc are now updated with the new Roq GitHub action :)

I've tried, to deploy a new project, after code.quarkus.io, you just need to enable GH page and restart the deploy workflow :)

**Comment by ia3andy** [comment]
@melloware @mcruzdev sorry for the CI spamming :)
