### ISSUE TITLE
duplicate title but unique file slugs cause exception

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-roq#241]
use the codestart and `cp content/posts/2024-10-13-the-first-roq.adoc content/posts/2024-11-01-other-post` and you get: 

```
 java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkiverse.roq.frontmatter.deployment.record.RoqFrontMatterInitProcessor#bindSite threw an exception: java.lang.IllegalStateException: Duplicate key posts/the-first-roqjj (attempted merging values Runtime proxy of interface java.util.function.Supplier with id proxykey1555 and Runtime proxy of interface java.util.function.Supplier with id proxykey1560)
```

digging in I see its because it has a `title` that is used for the slug ...not the filename.

I have two issues with that:

1) is using the title really the right thing? should it not be the slug derived from the file which then could be changed using `slug:` or similar?

2) the exception is very technical and does not give casual blog user much help. Would have expected some more meaningful and helpful; like "Duplicate slug ('the-first-roq') found. Check your titles and file names for duplication" or similar.

**Comment by ia3andy** [comment]
> I have two issues with that:
> 
> 1. is using the title really the right thing? should it not be the slug derived from the file which then could be changed using `slug:` or similar?

As explained in the doc: https://docs.quarkiverse.io/quarkus-roq/dev/quarkus-roq-frontmatter.html#link-placeholders

The default link for document is `/:collection/:slug`

 `:slug`: The slugified title of the page, derived from the title. Defaults to the slug property in data, if available or using the slugified title, falling back to the file name.

For page it uses the path.
 
> 2. the exception is very technical and does not give casual blog user much help. Would have expected some more meaningful and helpful; like "Duplicate slug ('the-first-roq') found. Check your titles and file names for duplication" or similar.

Yes we need to improve logging for sure overall, thanks for reporting this one.

**Comment by ia3andy** [comment]
We could change the default, this is only me choosing what seemed the more relevant... to me :)

**Comment by ia3andy** [comment]
Log is fixed
