### ISSUE TITLE
RSS: Top-level <link> tag should be an absolute url

### ISSUE THREAD

**Issue by jottinger** [quarkiverse/quarkus-roq#278]
Also, the entry links *can benefit from* being absolute links themselves, although the primary concern is the top-level link being incomplete.

**Comment by jottinger** [comment]
As far as the entry <link> tags, see https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt

The top level link: https://www.rssboard.org/rss-specification#requiredChannelElements

In both cases, they're absolute. That's a reference to RSS 2.0, but RSS 0.90 (the original spec) had similar suggestions: https://www.rssboard.org/rss-0-9-0 . 

Readers can generally get it "right" by inferring missing parts from the feed's URL itself (i.e., "this was loaded from 'http://foo.com/rss.xml, so the base url link is probably *meant to be* 'http://foo.com/'") but that's asking for compensatory code on the part of readers.

**Comment by dmlloyd** [comment]
This is pertaining to RSS (`rss.xml`) specifically, in case that wasn't clear from the report.

**Comment by melloware** [comment]
Oh let me look.  I copied what Gatsby was doing but maybe got this URL wrong.

**Comment by melloware** [comment]
Interesting here is my Gatsby generated one: https://www.melloware.com/rss.xml

it looks like Roqs: https://pages.quarkiverse.io/quarkus-roq/rss.xml

what am I not seeing specifically?

**Comment by melloware** [comment]
Also here is the Qute template an all URL's are absolute?  https://github.com/quarkiverse/quarkus-roq/blob/main/roq-frontmatter/runtime/src/main/resources/templates/fm/rss.html

**Comment by dmlloyd** [comment]
Here's mine: https://word-bits.flurg.com/rss.xml

Note also that "absolute URL" != "relative URL with an absolute path component".

**Comment by melloware** [comment]
@dmlloyd weird and you are on Roq 1.0.3?  I have no idea why those would be relative URLs when the code is doing `<link>{site.url.absolute}</link>`?

**Comment by dmlloyd** [comment]
Yeah here's my whole site, it's all open: https://github.com/dmlloyd/dmlloyd.github.io

**Comment by melloware** [comment]
I know why looking our Roq Blog it has this in application properties.

https://github.com/quarkiverse/quarkus-roq/blob/e6c975e585b1c7d455794e6e895c585140d20fe7/blog/src/main/resources/application.properties#L1C1-L2C47

**Comment by dmlloyd** [comment]
Ah: if it doesn't know the site URL, obviously the URL can't include it.

**Comment by melloware** [comment]
i think the docs for GitHub Pages need to be updated to include this info.

**Comment by melloware** [comment]
OK fixing the docs now!

**Comment by melloware** [comment]
actually in the GitHub Pages instructions it says do this..

```
run: mvn -B package quarkus:run -DskipTests -Dquarkus.http.root-path=$SITE_PATH -Dsite.url=$SITE_URL
```

So it knows your site path etc for you in your github actions?

**Comment by melloware** [comment]
can you both update your GitHub actions to this workflow from the docs.

https://docs.quarkiverse.io/quarkus-roq/dev/index.html#github-pages

It looks like Andy made this easier without that `gh-pages` profile.

**Comment by dmlloyd** [comment]
Joe's issue came from parsing the RSS feed from my site, so I'm the problem :)

I've fixed it using `application.properties` for now; I'll come back around and tinker with it later when I have more time. The main issue is that it's hard to test this kind of change offline and I don't want to mess up my site right now because then I can't really do anything else until it's fixed.

Thanks!

**Comment by melloware** [comment]
Thanks guys!
