### ISSUE TITLE
Clarifying path name conversion in static/assets

### ISSUE THREAD

**Issue by jotak** [quarkiverse/quarkus-roq#280]
Hi there,

First, thank you for the awesome work on Roq!
I'm [currently trying it](https://github.com/jotak/netobserv.github.io/) but had an issue about my images not being visible after ghpages deployment, although that was working well in the local run with `quarkus dev`.
It sounds like the static asset paths have been modified at some point with underscores `_` being replaced with hyphens `-`. E.g my original file `static/assets/images/whats_new_1_6/traffic_flows-grayed_out.png` now must be found at https://jotak.github.io/netobserv.github.io/static/assets/images/whats-new-1-6/traffic-flows-grayed-out.png

Is it something intended, is it some wrong configuration somewhere on my side, is it a bug? If intended maybe it should be documented [here](https://docs.quarkiverse.io/quarkus-roq/dev/index.html#_static_files) ?

**Comment by ia3andy** [comment]
Should be fixed already with latest release

**Comment by ia3andy** [comment]
https://github.com/quarkiverse/quarkus-roq/commit/987c8c09943ac86ed1d0abcf69771b5e16491c99

**Comment by melloware** [comment]
Yes @jotak please try 1.0.4 and report back?

**Comment by jotak** [comment]
Thanks, just tested and confirming it work 👌

**Comment by melloware** [comment]
@all-contributors add @jotak for test
