### ISSUE TITLE
cannot handle space in post names

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-roq#282]
I ended up with a file with a space in name - gives me error like this:

`java.lang.IllegalArgumentException: Invalid identifier found: [roq-gen/posts/2020-05-28-beyondhello copy]`

Might be valid issue but:

a) show the filename causing the issue
b) "identifier" is not something users know/should care about is it?

**Comment by ia3andy** [comment]
Yeah this should be easy to fix
