### ISSUE TITLE
Authors aren't displayed anymore

### ISSUE THREAD

**Issue by jtama** [quarkiverse/quarkus-roq#284]
I guess the culprit is here, but I don't know why :

https://github.com/quarkiverse/quarkus-roq/blob/main/theme/default/src/main/resources/templates/theme-layouts/roq-default/post.html#L46

I know the following does works : 

```
{#let pageAuthor in page.data.author}
{#let author=(cdi:authors.get(pageAuthor))}
....
```

**Comment by melloware** [comment]
@jtama PR please?

**Comment by jtama** [comment]
Will do that.
