### ISSUE TITLE
QRCode plugin doesn't work with asciidoc plugin

### ISSUE THREAD

**Issue by jtama** [quarkiverse/quarkus-roq#290]
It does with markdown which allows to write plain HTML but doesn't with asciidoc.

For asciidoc templates it should generate the image in the static folder and generate a link to it.

There is no access to the parent block in the section helper, so it's not possible to know what form should take the generated result.

We could add a type to the parameters to know if we should generate html or asciidoc code...

**Comment by melloware** [comment]
Good idea

**Comment by jtama** [comment]
So I have something that works. Kind of.

The size attributes aren't honored by yupiik asciidoctor renderer. So the image does render, but without any control on the size.

I created an issue, and can provide a PR, that will eventually work...

https://github.com/yupiik/tools-maven-plugin/issues/24
