### ISSUE TITLE
Give the ability to make posts series

### ISSUE THREAD

**Issue by jtama** [quarkiverse/quarkus-roq#294]
The idea is to be able to add specify that a post is part of a serie, and offer automatic navigation to other posts fro the same serie.

It gives strong coupling between multiple posts.

I know it exists at least on dev.to : 

![image](https://github.com/user-attachments/assets/3e0a3570-52c1-44e8-93dc-e4b72a90cac1)

I have made something for our internal use case, and added i18n for english and french, but I am not 100% percent I choose the right path. 

I can provide a PR as base for more discussion.

**Comment by ia3andy** [comment]
That would be a nice plugin.

Try to do it using the existing API, if it's not possible, let me know what's missing and we'll improve the api.

**Comment by jtama** [comment]
I have something already working.
I can provider a PR.
