### ISSUE TITLE
Move the Static Site Generation doc and getting started to the Roq Site

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#319]
During a Roq demo, @emmanuelbernard told me it would be better to have a doc outside the Quarkiverse one for the Static Site Gen part.

I also think that makes sense.

The idea is to move all the non standalone docs to the site (it shouldn't be too hard as we support asciidoc :) and have a link in the Quarkiverse doc pointing to the site.

**Comment by ia3andy** [comment]
I think I'll also request roq.quarkus.io (@maxandersen does that make sense?)

**Comment by maxandersen** [comment]
Not following the issue ?

On first hunch I wouldn't hook roq into Quarkus.io. It's in quarkiverse.

**Comment by ia3andy** [comment]
It's about not overwhelming users with Quarkiverse stuff when they hook in Roq and they shouldn't have to care if they don't want to...
