### ISSUE TITLE
Enable GitHub Action Marketplace

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#322]
![image](https://github.com/user-attachments/assets/8ddec8c0-f08f-4a34-aa77-2e16c52700ba)

@gastaldi 👆

**Comment by gastaldi** [comment]
Where do I see this UI and how do I get access to the Developer Agreement doc? I haveb't received any email about that

**Comment by gastaldi** [comment]
Found in https://github.com/quarkiverse/quarkus-roq/releases/edit/v1. Accepted. Go ahead ;)
