### ISSUE TITLE
Blog post about syntax highlighting is erroneous

### ISSUE THREAD

**Issue by jtama** [quarkiverse/quarkus-roq#323]
It states the following should be added to the `src/main/resources/web/app/main.scss`file : @import 'highlight.js/scss/default.scss';
When it should in fact be in `src/main/resources/web/app/main.js`

https://pages.quarkiverse.io/quarkus-roq/posts/how-to-add-syntax-highlighting-to-your-roq-site/

**Comment by ia3andy** [comment]
@jtama it should both work

**Comment by jtama** [comment]
Just retried locally, it doesn't. in quarkus dev mode.

**Comment by ia3andy** [comment]
Ok trying
