### ISSUE TITLE
default layout does not scale/resize well

### ISSUE THREAD

**Issue by maxandersen** [quarkiverse/quarkus-roq#331]
here is what default getting started shows on my screen - I have to go full screen to get something readable 

<img width="816" alt="2024-12-20_23-36-29" src="https://github.com/user-attachments/assets/fe03a5ee-cf41-498c-bc9a-e63c8e6cd185" />

here is how it renders when resizing

https://github.com/user-attachments/assets/72597a55-ccb7-43fa-ac3f-d54e89321652

**Comment by ia3andy** [comment]
that's a regression

**Comment by ia3andy** [comment]
This is fixed AFAIK. @maxandersen let me know..
