### ISSUE TITLE
Introduce a common deployement RoqObjectMapperBuiltItem

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#42]
Allow to configure a few things like the json naming strategy:
https://quarkus.io/guides/all-config#quarkus-jackson_quarkus-jackson-property-naming-strategy
https://quarkus.io/guides/all-config#quarkus-jackson_quarkus-jackson-fail-on-unknown-properties

and use it in Roq Data

**Comment by ia3andy** [comment]
@melloware interested? this should be fairly quick..

**Comment by melloware** [comment]
Yep let me look

**Comment by ia3andy** [comment]
We should use our own config for it (the example above are just to to show what's equivalent in Quarkus jackson runtime)

**Comment by melloware** [comment]
yep agreed we need our own ObjectMapper and settings.
