### ISSUE TITLE
[frontmatter] Add an easy way to deal with SEO

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-roq#80]
We need a similar feature set as https://github.com/jekyll/jekyll-seo-tag

**Comment by ia3andy** [comment]
@melloware do you want to have a look?

**Comment by ia3andy** [comment]
The idea is to provide a Qute `seo` tag which write important SEO stuff
The data is already available and consumable through `site.` or `page.`

**Comment by melloware** [comment]
Not sure i will be able to get to this in a reasonable amount of time.
